### ISSUE TITLE
壁を壊すタスクの組み込み

### ISSUE THREAD

**Issue by ichiharayuuma** [A-Classe/release_control#104]

**Comment by Matuyuhi** [comment]
組み込みがなんの事かわからんけど
以下でprogressに合わせて、4つの壁objの切り替え
https://github.com/A-Classe/release_control/pull/211

**Comment by ichiharayuuma** [comment]
壊れたときに最後のオブジェクトが表示されるようにしてください。
お願いします。

**Comment by Matuyuhi** [comment]
10/31
以下で実装
PR: https://github.com/A-Classe/release_control/pull/225
