### ISSUE TITLE
ステージのエフェクトの作成

### ISSUE THREAD

**Issue by ichiharayuuma** [A-Classe/release_control#138]
泡とか

**Comment by Matuyuhi** [comment]
@Nyasa0405 ここは最終的に何作ればいい？

**Comment by Nyasa0405** [comment]
泡、コースティック、煙も作ったし、光の柱も調整だけなら、あとはイチハラさんがどんな世界望んでるかによるかなぁ。（特に今は私からはない）
見つけたからアサインしてみたものの‥‥。

**Comment by Matuyuhi** [comment]
理解した。あざす

**Comment by ichiharayuuma** [comment]
いったんこのissueをクローズしようと思いますが、絶対やっておいたほうがいい作業はありますか
