### ISSUE TITLE
メインUIの作成

### ISSUE THREAD

**Issue by ichiharayuuma** [A-Classe/release_control#218]

**Comment by Matuyuhi** [comment]
10/26
とりあえず実装。
PR: https://github.com/A-Classe/release_control/pull/219

**Comment by ichiharayuuma** [comment]
早い実装ありがとうございます。
いくつか確認事項があります。
- 足りないアセットは同じブランチに追加していいですか？
- HPバーの緑色の部分は潜水艦の光っているところと同じ色にしてほしいです。
　体力が高ければみどり色、低ければ赤色に代わるようにしてください。
- 資源のメーターが増えるときに色がついた部分の境界の傾きが大きくなっていますが傾きをメーターの円弧の中心を常に通るようにしてほしいです。
　わかりにくいと思うので画像を添付します。
![resource](https://github.com/A-Classe/release_control/assets/109147088/9200031b-96ad-43d5-b237-0d4ea7829e6d)

- ワーカーの数を表すところの後ろのアニメーションの高さですが、ワーカーの数が0の時に波がぎりぎり見えるくらい、125の時にちょうど全部青色になるくらいにしてその間を線形補完する感じにしてほしいです。
- また、細かい部分ですがワーカーの数を表すところの外周の白い線をアニメーションより上に描画してほしいです。
　そのための線だけの画像も追加しておきます。
- ある程度進んだところから上部の距離が変化しなくなるのですがバグとしてissueを立てたほうがいいでしょうか。

忙しいとは思いますが対応お願いします。

**Comment by Matuyuhi** [comment]
修正しました

**Comment by ichiharayuuma** [comment]
ハンドルの動く範囲の修正とスライダーの色がHPに応じて変わるようにしました。
コードが汚かったら修正してください

**Comment by Matuyuhi** [comment]
@ichiharayuuma 
以下、修正内容です。
変数のformat等のwarning解消とlog削除です。
https://github.com/A-Classe/release_control/pull/219/commits/c724239c6f7d45e0a59729a2fd50ca3162380287
