### ISSUE TITLE
タスクができなくなるバグの修正

### ISSUE THREAD

**Issue by ichiharayuuma** [A-Classe/release_control#231]
IndexOutOfRangeException: Index was outside the bounds of the array.
(wrapper stelemref) System.Object.virt_stelemref_class_small_idepth(intptr,object)
Module.Assignment.System.WorkerAssigner.Update () (at Assets/Scripts/Module/Assignment/System/WorkerAssigner.cs:50)
Module.Assignment.System.AssignmentSystem.Tick () (at Assets/Scripts/Module/Assignment/System/AssignmentSystem.cs:103)
VContainer.Unity.TickableLoopItem.MoveNext () (at Library/PackageCache/jp.hadashikick.vcontainer@99c6e8c703/Runtime/Unity/PlayerLoopItem.cs:177)
VContainer.Unity.PlayerLoopRunner.Run () (at Library/PackageCache/jp.hadashikick.vcontainer@99c6e8c703/Runtime/Unity/PlayerLoopRunner.cs:64)
UnityEngine.Debug:LogException(Exception)
VContainer.Unity.PlayerLoopRunner:Run() (at Library/PackageCache/jp.hadashikick.vcontainer@99c6e8c703/Runtime/Unity/PlayerLoopRunner.cs:68)

上記のエラーが出てタスクができなくなる

**Comment by HarumaroJP** [comment]
修正しました
`fix/assigner-buffer`

**Comment by ichiharayuuma** [comment]
多分できてると思います。
