### ISSUE TITLE
壁を壊すタスク

### ISSUE THREAD

**Issue by HarumaroJP** [A-Classe/release_control#30]

**Comment by Matuyuhi** [comment]
8/29
ここで実装 : https://github.com/A-Classe/release_control/pull/63/commits/d8b34b2cf8c8491ce5599fb7a74eeb68d2c7abe2

**Comment by ichiharayuuma** [comment]
壊した後も当たり判定が残ってたけどこのタスクはDoneでいい？

**Comment by Matuyuhi** [comment]
⭕️

**Comment by HarumaroJP** [comment]
当たり判定が残る問題はここで修正完了
https://github.com/A-Classe/release_control/pull/80/commits/0e48bb9d83b1c120bdc6efd7a60437209afb9a35
