### ISSUE TITLE
壁を作るタスクの仮実装

### ISSUE THREAD

**Issue by Matuyuhi** [A-Classe/release_control#32]
壁を作ることで敵の進路を妨害する。敵は壁を壊そうとする

#33 ここと組み合わせる。というかここを先に作る

**Comment by HarumaroJP** [comment]
feature/create-wallに壁を作るところまでは実装しました。
DebugStageHaruシーンのStageObjects/StageTask1/CreateWallTaskを参考にしてください。

また、楕円の判定がオブジェクトの回転に依存してしまっているので、
DetectableAreaオブジェクトのAssinableArea→Rotationに回転角度の設定を追加しました。
光の角度を調節する際はそこをいじってください。
