### ISSUE TITLE
資源の収集・管理機能の実装

### ISSUE THREAD

**Issue by HarumaroJP** [A-Classe/release_control#34]

**Comment by ichiharayuuma** [comment]
NullReferenceException: Object reference not set to an instance of an object
Module.Player.Camera.CameraController.FixedUpdate () (at Assets/Scripts/Module/Player/Camera/CameraController.cs:31)

NullReferenceException: Object reference not set to an instance of an object
VContainer.Diagnostics.DiagnositcsContext+<>c__DisplayClass8_0.<FindByRegistration>b__0 (VContainer.Diagnostics.DiagnosticsInfo x) (at Library/PackageCache/jp.hadashikick.vcontainer@99c6e8c703/Runtime/Diagnostics/DiagnosticsContext.cs:53)
System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) (at <d630687edd41403db17561f5afda04df>:0)
System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <d630687edd41403db17561f5afda04df>:0)
VContainer.Diagnostics.DiagnositcsContext.FindByRegistration (VContainer.Registration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@99c6e8c703/Runtime/Diagnostics/DiagnosticsContext.cs:53)
VContainer.Diagnostics.DiagnosticsCollector.TraceResolve (VContainer.Registration registration, System.Func`2[T,TResult] resolving) (at Library/PackageCache/jp.hadashikick.vcontainer@99c6e8c703/Runtime/Diagnostics/DiagnosticsCollector.cs:59)
VContainer.ScopedContainer.Resolve (System.Type type) (at Library/PackageCache/jp.hadashikick.vcontainer@99c6e8c703/Runtime/Container.cs:76)

この2種類のエラーが出てゲームが進行しないです

**Comment by ichiharayuuma** [comment]
Main CameraのVolume TriggerとContainerの何かしらがセットされていないみたいです

**Comment by HarumaroJP** [comment]
多分今WorkerTest_NavMeshが壊れてるので、StageCreateTestでテストしてみてください。
ダメだったらUnity再起動で治ると思います。

**Comment by ichiharayuuma** [comment]
動きました
こっちの言葉足らずで申し訳ないのですが、タスクが中断された場合は集めている途中の資源は潜水艦に渡されません。
タスクが中断された場合は状態を保存するだけにとどめます。
タスクが完了したときにもし集めている途中の資源があったらその分が潜水艦に渡されます。

**Comment by HarumaroJP** [comment]
あ、その仕様忘れてキャンセル時と完了時の処理一緒にしちゃってました。sorry
バイト終わったら直します！

**Comment by HarumaroJP** [comment]
修正したので確認してみてください

**Comment by ichiharayuuma** [comment]
確認しました
