### ISSUE TITLE
操る機能の改善

### ISSUE THREAD

**Issue by HarumaroJP** [A-Classe/release_control#48]

**Comment by Matuyuhi** [comment]
@HarumaroJP 
なんかworkerの割り当てとかで挙動がおかしいのはここの修正で合ってる？

**Comment by HarumaroJP** [comment]
タスクの一点に集まっちゃうやつ？
それはまだ直してないかも

**Comment by Matuyuhi** [comment]
タスク終わった後に帰ってこなくなる。正確には追尾判定にはなっているけど、自機の近くまで戻ってこない。
コンフリクトの時になんか変になっただけかも

**Comment by HarumaroJP** [comment]
あーごめんそれキャラ増やす方のタスクで直しちゃったかも

**Comment by Matuyuhi** [comment]
OK。治ってた。あざます
