### ISSUE TITLE
タイトル画面(TL OO)の実装

### ISSUE THREAD

**Issue by Matuyuhi** [A-Classe/release_control#76]

**Comment by Matuyuhi** [comment]
https://miro.com/app/board/uXjVMzA76LE=/?moveToWidget=3458764562482509956&cot=14 
この辺りからのタイトル画面の実装。
各機能との紐付けは多分後で

**Comment by Matuyuhi** [comment]
8/29
画面の遷移まで実装済み
ここ : https://github.com/A-Classe/release_control/commit/5c03f4fa4326391a5d52f08b120056ab0214836d

**Comment by Matuyuhi** [comment]
8/31
https://github.com/A-Classe/release_control/pull/85 : ここのデータ保存との紐付けで更新
https://github.com/A-Classe/release_control/issues/87: ここにもあるが、確定まで待ち

**Comment by Matuyuhi** [comment]
@ichiharayuuma より
やること

・戻ったら前の画面の選択状態にする
・フェードアウトのタイミングをボタンが押されたらにする
・バー横の四角の大きさをアニメーションに合わせて変える
・カーソルの位置を合わせる
・シーンが切り替わってすぐ、カーソルの幅があってないのを直す

**Comment by Matuyuhi** [comment]
@ichiharayuuma 
feature/title-screen-uiブランチのResourceフォルダ内にタイトルロゴのファイルがありますが、これはまだシーンには配置しないという事であってますか？

**Comment by ichiharayuuma** [comment]
配置します。
その他にもカーソルも新しいのに変えてください。
お願いします

**Comment by Matuyuhi** [comment]
10/26
すでに10/25にdevelopにマージ済みであるが、
一応ここ
PR: https://github.com/A-Classe/release_control/pull/214
