### ISSUE TITLE
墨ゾーンの実装

### ISSUE THREAD

**Issue by Ayane2003** [A-Classe/release_control#90]

**Comment by HarumaroJP** [comment]
> 形は比重や温度が異なる液体が混ざったときのように、滲むのではなくとどまるように海底に広がります。
> スクリューのタスクが完了してすぐに機能は停止して、墨自体はスクリューの作った海流の通り道から端に向かって急速にフェードアウトします。
 
要するに、こういうのが海底に広がっていく感じですか？
https://youtu.be/Xt3IN0Ggyhg?t=77

**Comment by ichiharayuuma** [comment]
そうです。
