### ISSUE TITLE
ワーカーの操り方を光の範囲で操るようにする

### ISSUE THREAD

**Issue by ichiharayuuma** [A-Classe/release_control#97]

**Comment by HarumaroJP** [comment]
仕様通りに実装はしました。個人的には前の方が好きです。
light-based-moveブランチのStageCreateTestシーンでテストしてください。


ゲーム開始時の明るさを調整するには
プレイヤーは
Player→Leader→DetectableArea→AssignableAreaコンポーネントのIntensityを調整することで変更できます。

タスクは
シーン上のタスクのprefab→DetectableArea→AssignableAreaコンポーネントのIntensityを調整することで変更できます。


光のぼかすには、
シーン上のタスクのprefab→DetectableArea→AreaLightのマテリアルのRadius, Softnessを調節すると出来ます。
やや癖が強いので、調整は少し面倒かもしれないです。

**Comment by HarumaroJP** [comment]
あと、割り当てボタン、解除ボタンを押したときの明るさの変化は
Assetsフォルダ→Settings→GameParam→GameParam
のAssign or Release Intensityで変えられます。まだ仮実装なので、フェードなどの処理は実装してません。

**Comment by ichiharayuuma** [comment]
連絡が遅くなってしまって申し訳ないのですが、動き方を前の仕様に戻してほしいです。
動かしてみた結果、前のほうがよかったと判断しました。
見た目に関しては現状のままでお願いします。

具体的には
Aボタンで割り振り
Bボタンで回収
タスクの範囲と重なったワーカーがタスクに配置される
操る光と重なったワーカーが回収される
タスクを終了させたらワーカーはリーダーに帰ってくる

というふうにしてほしいです
よろしくお願いします

**Comment by HarumaroJP** [comment]
了解しました

**Comment by HarumaroJP** [comment]
再度実装し直しました。
仕様の内容的には、前の仕様と明るさベースの仕様を組み合わせた新たな仕様のようなので
確認が終わり次第、Miroなどで仕様を整理しておいてもらえるとありがたいです。

また、このシステムの実装が完了次第、タスクの設定方法が確定するのでドキュメントにまとめてみます。

**Comment by ichiharayuuma** [comment]
確認しました。
動きとしてはいと思います。
回収した時やタスクが完了した時にワーカーがついてこないときがあるのですがバグでしょうか。

**Comment by HarumaroJP** [comment]
おそらくですが、設定されている割り当て座標より多くのワーカーが割り当てられようとすると、ついてこないと思います。
コンソールに「登録できるAssignPointはありません！」と表示されていたらそれです。

自動生成もありっちゃありなんですが、実装コストが高いので、
仕様をよく話し合った上で後半で実装できたらしようかなと思ってます。

**Comment by HarumaroJP** [comment]
あでも画面外に行ったときは回収されていなかったようなので、それは今修正しました。

**Comment by ichiharayuuma** [comment]
修正ありがとうございます。
miroには後で書いておきます。
